name: Node.js CI
on: [push]
jobs :
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.5
        with :
          ftp-server: 47.102.219.203
          ftp-username: ${{ secrets.ftp_user }}
          ftp-password: ${{ secrets.ftp_pwd }}
          port: 21
          local-dir: build/
        env:
          CI: true